# Generated by Django 3.0.7 on 2020-07-05 04:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userleaguestatus',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('umpire', 'umpire'), ('manager', 'manager'), ('inactive', 'inactive')], default='inactive', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 4, 8, 6, 255625, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='userleaguestatus',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 4, 8, 6, 258146, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userleaguestatus',
            name='date_pending',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 4, 8, 6, 258126, tzinfo=utc)),
        ),
    ]
