# Generated by Django 3.0.7 on 2020-07-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_configured'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleaguestatus',
            name='max_backups',
            field=models.IntegerField(default=0),
        ),
    ]
