# Generated by Django 3.0.7 on 2020-07-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20200730_1959'),
        ('users', '0003_userleaguestatus_max_backups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleaguestatus',
            name='visibilities',
            field=models.ManyToManyField(blank=True, to='leagues.Role'),
        ),
    ]
