# Generated by Django 3.0.7 on 2020-07-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_level'),
        ('users', '0004_auto_20200722_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleaguestatus',
            name='visibility',
            field=models.ManyToManyField(to='leagues.Role'),
        ),
    ]
