# Generated by Django 3.0.7 on 2020-07-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200730_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='userleaguestatus',
            options={'ordering': ['-pk']},
        ),
    ]
