# Generated by Django 3.0.7 on 2020-07-24 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userleaguestatus_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userleaguestatus',
            old_name='visibility',
            new_name='visibilities',
        ),
    ]
