# Generated by Django 3.0.7 on 2020-08-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200731_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='application_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='game_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='league_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
