# Generated by Django 3.0.7 on 2020-07-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200724_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userleaguestatus',
            name='join_status',
        ),
        migrations.AddField(
            model_name='userleaguestatus',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
