# Generated by Django 3.0.7 on 2020-07-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200726_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userleaguestatus',
            name='is_pending',
        ),
        migrations.AddField(
            model_name='userleaguestatus',
            name='request_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
