# Generated by Django 3.0.7 on 2020-08-19 19:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0008_league_cancellation_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSnapNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='TeamSnapNoteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=128)),
                ('teamsnap_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamsnap.TeamSnapNote')),
            ],
        ),
    ]
