# Generated by Django 3.0.7 on 2020-08-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-pk']},
        ),
    ]
