# Generated by Django 3.0.7 on 2020-08-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200807_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
