# Generated by Django 3.0.7 on 2020-07-29 04:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import leagues.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('ts_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=1028, null=True)),
                ('league_picture', models.ImageField(blank=True, null=True, upload_to='league_pics/%Y/%m/')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField(default=leagues.models.set_league_expiration_date)),
                ('adv_scheduling_limit', models.IntegerField(default=30)),
                ('public_access', models.BooleanField(default=False)),
                ('can_apply', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=64, null=True)),
                ('website_url', models.CharField(blank=True, max_length=64, null=True)),
                ('ts_id', models.IntegerField(default=0)),
                ('api_key', models.CharField(default='', max_length=128)),
                ('opponent_library', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.Division')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
                ('roles', models.ManyToManyField(to='leagues.Role')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='division',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League'),
        ),
    ]
