# Generated by Django 3.0.7 on 2020-07-05 04:08

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('ts_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='adv_scheduling_limit',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='league',
            name='api_key',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='league',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 4, 8, 6, 252720, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='league',
            name='description',
            field=models.TextField(blank=True, max_length=1028, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 4, 8, 6, 252749, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='league',
            name='league_picture',
            field=models.ImageField(blank=True, null=True, upload_to='league_pics/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='league',
            name='opponent_library',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='league',
            name='ts_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='league',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.Division')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League'),
        ),
        migrations.CreateModel(
            name='ApplyLeagueCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2020, 7, 12, 4, 8, 6, 253528, tzinfo=utc))),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
            ],
        ),
    ]
