# Generated by Django 3.0.7 on 2020-07-05 04:14

from django.db import migrations, models
import django.utils.timezone
import leagues.models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20200705_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleaguecode',
            name='expiration_date',
            field=models.DateTimeField(default=leagues.models.set_apply_league_expiration_date),
        ),
        migrations.AlterField(
            model_name='league',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='league',
            name='expiration_date',
            field=models.DateTimeField(default=leagues.models.set_league_expiration_date),
        ),
    ]
