# Generated by Django 3.0.7 on 2020-07-30 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20200729_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='roles',
            new_name='visibilities',
        ),
    ]
