# Generated by Django 3.0.7 on 2020-07-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20200730_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='default_max_backup',
            new_name='default_max_backups',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='default_max_cast',
            new_name='default_max_casts',
        ),
    ]
