# Generated by Django 3.0.7 on 2020-07-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20200705_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='public_access',
            field=models.BooleanField(default=False),
        ),
    ]
