# Generated by Django 3.0.7 on 2020-07-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_league_public_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='can_apply',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='title',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='league',
            name='title',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='ApplyLeagueCode',
        ),
    ]
