# Generated by Django 3.0.7 on 2020-07-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_auto_20200731_0356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['-pk']},
        ),
    ]
