# Generated by Django 3.0.7 on 2020-07-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='website_url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
