# Generated by Django 3.0.7 on 2020-08-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_auto_20200819_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
