# Generated by Django 3.0.7 on 2020-08-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_league_is_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
