# Generated by Django 3.0.7 on 2020-10-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_trigram_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='title',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
