# Generated by Django 3.0.7 on 2020-10-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0014_auto_20201010_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='title',
            field=models.CharField(default='existing default', max_length=32),
            preserve_default=False,
        ),
    ]
