# Generated by Django 3.0.7 on 2020-08-08 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0003_auto_20200807_0216'),
        ('leagues', '0008_league_cancellation_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_date_time', models.DateTimeField()),
                ('subject', models.CharField(blank=True, max_length=64, null=True)),
                ('message', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UmpCastNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.BaseNotification')),
            ],
            bases=('notifications.basenotification',),
        ),
        migrations.CreateModel(
            name='LeagueNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.BaseNotification')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
            ],
            bases=('notifications.basenotification',),
        ),
        migrations.CreateModel(
            name='GameNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.BaseNotification')),
                ('was_reminded', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
            bases=('notifications.basenotification',),
        ),
        migrations.CreateModel(
            name='ApplicationNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.BaseNotification')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Application')),
            ],
            bases=('notifications.basenotification',),
        ),
    ]
