# Generated by Django 3.0.7 on 2020-08-12 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basenotification',
            name='notification_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
